# Generated by Django 3.2.8 on 2021-11-22 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Shoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('description', models.TextField(max_length=1000)),
                ('for_man', models.BooleanField(default=True)),
                ('for_child', models.BooleanField(default=True)),
                ('image', models.ImageField(upload_to='images/')),
                ('country', models.TextField(max_length=50)),
                ('company', models.TextField(max_length=100)),
                ('price', models.PositiveIntegerField(default=0)),
                ('is_purchasable', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=20)),
                ('surname', models.TextField(max_length=20)),
                ('email', models.EmailField(max_length=30)),
                ('password', models.TextField(max_length=20)),
                ('phone', models.TextField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Shoes_material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab3_app.materials')),
                ('shoe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab3_app.shoes')),
            ],
        ),
        migrations.CreateModel(
            name='Shoes_count',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.TextField()),
                ('count', models.PositiveIntegerField(default=0)),
                ('shoe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab3_app.shoes')),
            ],
        ),
        migrations.CreateModel(
            name='Shoes_colors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab3_app.colors')),
                ('shoe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab3_app.shoes')),
            ],
        ),
        migrations.CreateModel(
            name='Carts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.TextField()),
                ('count', models.PositiveIntegerField()),
                ('active', models.BooleanField(default=False)),
                ('shoe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab3_app.shoes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab3_app.users')),
            ],
        ),
    ]
